<a href="https://colab.research.google.com/github/vchandraiitk/datascience/blob/main/Vikas_M2_NB_MiniProject_2_Linear_Algebra_and_Calculus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Advanced Certification Program in Computational Data Science
## A program by IISc and TalentSprint
### Mini Project Notebook: Linear Algebra and Calculus

## Problem Statement

 The task is to advise a petroleum company on how to meet the demands of their customers for motor oil, diesel oil and gasoline.

## Learning Objectives

At the end of the experiment, you will be able to

* create arrays and matrices in python
* understand the concepts of linear equations
* solve the system of linear equations

### Data

From a barrel of crude oil, in one day, factory $A$ can produce
* 20 gallons of motor oil,
* 10 gallons of diesel oil, and
* 5 gallons of gasoline

Similarly, factory $B$ can produce
* 4 gallons of motor oil,
* 14 gallons of diesel oil, and
* 5 gallons of gasoline

while factory $C$ can produce
* 4 gallons of motor oil,
* 5 gallons of diesel oil, and
* 12 gallons of gasoline

There is also waste in the form of paraffin, among other things. Factory $A$ has 3 gallons of paraffin to dispose of per barrel of crude, factory $B$ 5 gallons, and factory $C$ 2 gallons.

**Note:** Your conclusion should include a discussion of the nature of the terms *unique*, *no solution*, *overdetermined* and *underdetermined* as they apply in the context of the oil plants.

## Grading = 10 Points

### Create an array

Create an array of size 2x3 with arbitrary values.

In [31]:
#TASK-1 (With Array)
# YOUR CODE HERE
import numpy as np
##randint is for geneting integer numbers and not float
#100 means it will geneate any number less than 100.
np.random.randint(100, size=(2, 3))

array([[33, 28,  6],
       [76, 80, 76]])

In [32]:
##TASK-1 (With Matrix)
matrix1 = np.matrix([[0, 4, 16],
                     [16, 4, 0]])
matrix1

matrix([[ 0,  4, 16],
        [16,  4,  0]])

### Create the system of Linear Equations

Suppose the current daily demand from distributors is 6600 gallons of motor oil, 5100 gallons of diesel oil and 3100 of gasoline.

Set up the system of equations which describes the above situation. Please include the units as well.

Let the number of barrels used by factory $A$, $B$ and $C$ are $x$, $y$ and $z$ respectively.

Then the system of linear equations will be

$$Motor\ oil:\ \ \ 20x + 4y + 4z = 6600$$

$$Diesel\ oil:\ \ \ 10x + 14y + 5z = 5100$$

$$Gasoline:\ \ \ 5x + 5y + 12z = 3100$$

### Solve the system of Linear Equation (2 points)

How many barrels of crude oil each plant should get in order to meet the demand as a group. Remember that we can only provide each plant with an integral number of barrels.

In [64]:
#TASK-2
# YOUR CODE HERE
from scipy import linalg
import numpy as np

A = np.array([[20,4,4],
             [10,14,5],
             [5,5,12]])
b = np.array([6600,5100,3100])
x = linalg.solve(A,b)
round_x = np.round(x).astype(int)
round_x
print("Number of barrels of crude oil each plant should get are {} {} {} for A, B, C respectively".format(math.ceil(float(x[0])), math.ceil(float(x[1])), math.ceil(float(x[2]))))

Number of barrels of crude oil each plant should get are 288 129 85 for A, B, C respectively


In [34]:
#TASK-2
# YOUR CODE HERE
from sympy import symbols, Eq, solve
import math
x, y, z = symbols('x,y,z')
motor_oil_eq = Eq((20*x+4*y+4*z), 6600)
diesel_oil_eq = Eq((10*x+14*y+5*z), 5100)
gasoline_oil_eq = Eq((5*x+5*y+12*z), 3100)
dir = solve((motor_oil_eq, diesel_oil_eq, gasoline_oil_eq), (x,y,z))
x = math.ceil(float(dir.get(x)))
y = math.ceil(float(dir.get(y)))
z = math.ceil(float(dir.get(z)))
x,y,z

(288, 129, 85)

Suppose the total demand for all products **doubled**. What would the solution now be? How does it compare to the original solution? Why, mathematically, should this have been expected?

In [65]:
#TASK-3
# YOUR CODE HERE
b_new = 2*b
x_new = linalg.solve(A,b_new)
round_x_new = np.round(x_new).astype(int)
round_x_new
print("Number of barrels of crude oil each plant should get are {} {} {} for A, B, C respectively".format(math.ceil(float(x_new[0])), math.ceil(float(x_new[1])), math.ceil(float(x_new[2]))))

Number of barrels of crude oil each plant should get are 575 258 170 for A, B, C respectively


In [37]:
#TASK-3
# YOUR CODE HERE
from sympy import symbols, Eq, solve
import math
x, y, z = symbols('x,y,z')
motor_oil_eq = Eq((20*x+4*y+4*z), 13200)
diesel_oil_eq = Eq((10*x+14*y+5*z), 10200)
gasoline_oil_eq = Eq((5*x+5*y+12*z), 6200)
dir = solve((motor_oil_eq, diesel_oil_eq, gasoline_oil_eq), (x,y,z))
x = math.ceil(float(dir.get(x)))
y = math.ceil(float(dir.get(y)))
z = math.ceil(float(dir.get(z)))
x,y,z

(575, 258, 170)

Suppose that the company acquires another group of distributors and that the daily demand of this group is 2000 gallons of motor oil, 4000 gallons of gasoline, and 4000 gallons of diesel oil. How would you set up production of just this supply? Are there any options (more than one way)?

In [66]:
#TASK-4
# YOUR CODE HERE
b_new2 = np.array([2000,4000,4000])
x_new2 = linalg.solve(A,b_new2)
round_x_new2 = np.round(x_new2).astype(int)
round_x_new2
print("Number of barrels of crude oil each plant should get are {} {} {} for A, B, C respectively".format(math.ceil(float(x_new2[0])), math.ceil(float(x_new2[1])), math.ceil(float(x_new2[2]))))

Number of barrels of crude oil each plant should get are 13 188 250 for A, B, C respectively


In [40]:
#TASK-4
# YOUR CODE HERE
x, y, z = symbols('x,y,z')
motor_oil_eq = Eq((20*x+4*y+4*z), 2000)
diesel_oil_eq = Eq((10*x+14*y+5*z), 4000)
gasoline_oil_eq = Eq((5*x+5*y+12*z), 4000)
dir = solve((motor_oil_eq, diesel_oil_eq, gasoline_oil_eq), (x,y,z))
x = math.ceil(float(dir.get(x)))
y = math.ceil(float(dir.get(y)))
z = math.ceil(float(dir.get(z)))
x,y,z

(13, 188, 250)

In [41]:
#TASK-4 (Alternate Solution)
# Coefficient matrix A
A = np.array([[20, 4, 4], [10, 14, 5], [5, 5, 12]])

# Constant matrix B
B = np.array([2000, 4000, 4000])

X = np.linalg.solve(A, B)
math.ceil(float(X[0])), math.ceil(float(X[1])), math.ceil(float(X[2]))

(13, 188, 250)

Next, calculate the needs of each factory (in barrels of crude, as usual) to meet the total demand of both groups of distributors. When you have done this, compare your answer to results already obtained. What mathematical conclusion can you draw?

In [67]:
#TASK-5
# YOUR CODE HERE
b_total = b+b_new2
x_total = linalg.solve(A,b_total)
round_x_total = np.round(x_total).astype(int)
round_x_total
print("Number of barrels of crude oil each plant should get are {} {} {} for A, B, C respectively".format(math.ceil(float(x_total[0])), math.ceil(float(x_total[1])), math.ceil(float(x_total[2]))))

Number of barrels of crude oil each plant should get are 300 317 335 for A, B, C respectively


In [43]:
#TASK-5
# YOUR CODE HERE
x, y, z = symbols('x,y,z')
motor_oil_eq = Eq((20*x+4*y+4*z), 8600)
diesel_oil_eq = Eq((10*x+14*y+5*z), 9100)
gasoline_oil_eq = Eq((5*x+5*y+12*z), 7100)
dir = solve((motor_oil_eq, diesel_oil_eq, gasoline_oil_eq), (x,y,z))
x = math.ceil(float(dir.get(x)))
y = math.ceil(float(dir.get(y)))
z = math.ceil(float(dir.get(z)))
x,y,z

(300, 317, 335)

### Sensitivity and Robustness (1 point)

In real life applications, constants are rarely ever exactly equal to their stated value; certain amounts of uncertainty are always present. This is part of the reason for the science of statistics. In the above model, the daily productions for the plants would be averages over a period of time. Explore what effect small changes in the parameters have on the output.

To do this, pick any 3 coefficients, one at a time, and increase or decrease them by 3%. For each case , note what effect this has on the solution, as a percentage change. Can you draw any overall conclusion?

In [68]:
#TASK-6
# YOUR CODE HERE
# Increase co-effients of Factory A by 3%
A_inc_3 = A.astype(float)
A_inc_3[:, 0] = A_inc_3[:, 0] * 1.03
x_inc_3 = linalg.solve(A_inc_3,b)
round_x_inc_3 = np.round(x_inc_3).astype(int)
print("****Case-1: Coefficients of Factory A is Increased by 3% ****")
print("Number of barrels of crude oil each plant should get are {} {} {} for A, B, C respectively".format(round_x_inc_3[0],round_x_inc_3[1],round_x_inc_3[2]))

print("\n\n")

# Decrease co-efficients of Factory B by 3%
B_dec_3 = A.astype(float)
B_dec_3[:, 1] = B_dec_3[:, 1] * 0.97
x_dec_3 = linalg.solve(B_dec_3,b)
round_x_dec_3 = np.round(x_dec_3).astype(int)
print("****Case-2: Coefficients of Factory B is Decreased by 3% ****")
print("Number of barrels of crude oil each plant should get are {} {} {} for A, B, C respectively".format(round_x_dec_3[0],round_x_dec_3[1],round_x_dec_3[2]))

****Case-1: Coefficients of Factory A is Increased by 3% ****
Number of barrels of crude oil each plant should get are 279 129 85 for A, B, C respectively



****Case-2: Coefficients of Factory B is Decreased by 3% ****
Number of barrels of crude oil each plant should get are 287 133 85 for A, B, C respectively


In [46]:
#TASK-6
# YOUR CODE HERE
# Coefficient matrix A
A = np.array([[20, 4, 4], [10, 14, 5], [5, 5, 12]], dtype=float)
arrayCopy=A.copy()
print("-----For (+3%) Start---------")
coeff_arr = [0.03, -0.03]
for coeff in coeff_arr:
    print(f"------------Starting for coefficient {coeff}------------")
    for i in range(len(A)):
        for j in range(len(A[i])):
            A[j][i] += A[j][i]*coeff
            print(f"Setting for row {j}, column{i} & coeff=({coeff})")
        B = np.array([15200, 14200, 10200])
        X = np.linalg.solve(A, B)
        print(" ")
        print(f"{math.ceil(float(X[0]))} , {math.ceil(float(X[1]))}, {math.ceil(float(X[2]))}")
        print(" ")
        A=arrayCopy.copy()
    print(f"------------Finished for coefficient {coeff}------------")

-----For (+3%) Start---------
------------Starting for coefficient 0.03------------
Setting for row 0, column0 & coeff=(0.03)
Setting for row 1, column0 & coeff=(0.03)
Setting for row 2, column0 & coeff=(0.03)
 
570 , 445, 420
 
Setting for row 0, column1 & coeff=(0.03)
Setting for row 1, column1 & coeff=(0.03)
Setting for row 2, column1 & coeff=(0.03)
 
587 , 433, 420
 
Setting for row 0, column2 & coeff=(0.03)
Setting for row 1, column2 & coeff=(0.03)
Setting for row 2, column2 & coeff=(0.03)
 
587 , 445, 408
 
------------Finished for coefficient 0.03------------
------------Starting for coefficient -0.03------------
Setting for row 0, column0 & coeff=(-0.03)
Setting for row 1, column0 & coeff=(-0.03)
Setting for row 2, column0 & coeff=(-0.03)
 
606 , 445, 420
 
Setting for row 0, column1 & coeff=(-0.03)
Setting for row 1, column1 & coeff=(-0.03)
Setting for row 2, column1 & coeff=(-0.03)
 
587 , 459, 420
 
Setting for row 0, column2 & coeff=(-0.03)
Setting for row 1, column2 & coef

### A Plant Off-Line (1 point)

Suppose factory $C$ is shut down by the EPA (Environmental Protection Agency) temporarily for excessive emissions into the atmosphere. If your demand is as it was originally (6600, 5100, 3100), what would you now say about the companies ability to meet it? What do you recommend they schedule for production now?

In [69]:
#TASK-7
# YOUR CODE HERE
# Factory C shut
from scipy.linalg import lstsq
C_shut = A

# Remove the column associated with Factory C
C_shut = np.delete(C_shut,2,1)

# Solve the system using lstsq
solution, residuals, rank, singular_values = lstsq(C_shut,b)
print("Number of barrels of crude oil each plant should get are {} {} for A, B".format(solution[0],solution[1]))

Number of barrels of crude oil each plant should get are 299.4720496894411 168.4782608695653 for A, B


### Buying another plant

####(Note the following given information. You will see questions in continuation to this, in the subsequent sections)

This situation has caused enough concern that the CEO is considering buying another plant, identical to the third, and using it permanently. Assuming that all 4 plants are on line, what production do you recommend to meet the current demand (5000, 8500, 10000)? In general, what can you say about any increased flexibility that the 4th plant might provide?

Let the number of barrels used by factory $A$, $B$, $C$ and $D$ are $x$, $y$, $z$ and $w$ respectively.

Then the system of linear equations will be

$$20x + 4y + 4z + 4w = 5000$$

$$10x + 14y + 5z + 5w = 8500$$

$$5x + 5y + 12z + 12w = 10000$$

The above system of linear equation has fewer equations than variables, hence it is *underdetermined* and cannot have a unique solution. In this case, there are either infinitely many solutions or no exact solution. We can solve it by keeping $w$ as constant and using [rref](http://linear.ups.edu/html/section-RREF.html) form to solve the system of linear equation.

To know about rref implementation in python refer [here](https://docs.sympy.org/latest/tutorial/matrices.html#rref).

In [70]:
import sympy as sy

# create symbol 'w'
w = sy.Symbol("w")
A_aug = sy.Matrix([[20, 4, 4, 5000-4*w],
                   [10, 14, 5, 8500-5*w],
                   [5, 5, 12, 10000-12*w]])
# show rref form
A_aug.rref()

(Matrix([
 [1, 0, 0,   195/4],
 [0, 1, 0,  1325/4],
 [0, 0, 1, 675 - w]]),
 (0, 1, 2))

From the above result, it can be seen that 4th plant will share the number of barrels required by the 3rd plant only, while the requirement of 1st and 2nd plant will remain unaffected.

### Calculate the amount of Paraffin supplied (1 point)

The company has just found a candle company that will buy its paraffin. Under the current conditions (i.e, after buying another plant) for demand (5000, 8500, 10000), how much can be supplied to them per day?

According to the problem statement, factory $A$ has 3 gallons of paraffin to dispose of per barrel of crude oil, factory $B$ 5 gallons, and factory $C$ 2 gallons.

In [71]:
#TASK-8
# YOUR CODE HERE
x=195/4
y=1325/4
z=675-w
production=x*3+y*5+z*2
print(production)
#w is constant,
#   if w value is high then total production will be negative and that's not possible
#   if w is very small then overall production will be around 3152.5 gallons


3152.5 - 2*w


In [72]:
#TASK-8 (With Assumption)
# YOUR CODE HERE
# Since A and B are unaffected and C&D share the barrel
import numpy as np
paraffin_per_barrel = np.array([3, 5, 2, 2])
barrels_per_factory = np.append(round_x, round_x[2])
print(barrels_per_factory)
paraffin_total = np.sum(paraffin_per_barrel * barrels_per_factory)
print("Total amount of paraffin generated: ", paraffin_total)

[287 129  85  85]
Total amount of paraffin generated:  1846


### Selling the first plant (1 point)

The management is also considering selling the first plant due to aging equipment and high workman's compensation costs for the state it is located in. They would like to know what this would do to their production capability. Specifically, they would like an example of a demand they could not meet with only plants 2 and 3, and also what effect having plant 4 has (recall it is identical to plant 3). They would also like an example of a demand that they could meet with just plants 2 and 3. Any general statements you could make here would be helpful.

Let the number of barrels used by factory $B$, $C$ and $D$ are $y$, $z$ and $w$ respectively.

When considering only plants 2 and 3, and demand (5000, 8500, 10000) then we have

$$4y + 4z = 5000$$

$$14y + 5z = 8500$$

$$5y + 12z = 10000$$

In [51]:
#TASK-9
# YOUR CODE HERE
# Factory A is sold
from scipy.linalg import lstsq
A_sell = A
# Remove the column associated with Factory A
A_shut = np.delete(A_sell,0,1)

new_demand = np.array([5000,8500,10000])

# Solve the system using lstsq
solution, residuals, rank, singular_values = lstsq(A_sell,new_demand)

print("Number of barrels of crude oil each plant should get are {} {} for B, C".format(solution[0],solution[1]))

Number of barrels of crude oil each plant should get are 48.75000000000023 331.2500000000001 for B, C


Taking 4th plant into consideration.
Let the number of barrels used by factory $B$, $C$ and $D$ are $y$, $z$ and $w$ respectively.

Then for demand (5000, 8500, 10000) the system of linear equations will be

$$4y + 4z + 4w = 5000$$

$$14y + 5z + 5w = 8500$$

$$5y + 12z + 12w = 10000$$

Solve it using rref form.

In [53]:
#TASK-10
# YOUR CODE HERE
import sympy as sy

B_aug = sy.Matrix([[4, 4, 4, 5000],
                   [14, 5, 5, 8500],
                   [5, 12, 12, 10000]])
# show rref form
B_aug.rref()

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 1, 0],
 [0, 0, 0, 1]]),
 (0, 1, 3))

Now, changing demand to (6600, 5100, 3100) and solving the system of equation using rref form.

In [54]:
#TASK-11
# YOUR CODE HERE
B_aug = sy.Matrix([[4, 4, 4, 6600],
                   [14, 5, 5, 5100],
                   [5, 12, 12, 3100]])
# show rref form
B_aug.rref()

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 1, 0],
 [0, 0, 0, 1]]),
 (0, 1, 3))

### Set rates for Products (1 point)

Company wants to set the rates of motor oil, diesel oil, and gasoline. For this purpose they have few suggestions given as follows:

* 100, 66, 102 Rupees per gallon,

* 104, 64, 100 Rupees per gallon,

* 102, 68, 98 Rupees per gallon, and

* 96, 68, 100 Rupees per gallon

for motor oil, diesel oil, and gasoline respectively.

Using matrix multiplication, find the rates which result in maximum total price.

Let $M$ denote the matrix such that rows represents different plants (A, B and C), columns represents different products (motor oil, diesel oil and gasoline) and each value represents production of that product from one barrel of crude oil for that plant.

$$M = \begin{bmatrix}
20 & 10 & 5 \\
4 & 14 & 5  \\
 4 & 5 & 12  
\end{bmatrix}$$

Also, $R$ is a matrix having different rates as its columns.

$$R = \begin{bmatrix}
100 & 104 & 102 & 96 \\
66 & 64 & 68 & 68  \\
102 & 100 & 98 & 100  
\end{bmatrix}$$

In [55]:
#TASK-12
# YOUR CODE HERE
M = np.array(
    [[20, 10,  5],
     [4, 14, 5],
      [4, 5, 12]])
R = np.array(
    [[100, 104, 102, 96],
     [66, 64, 68, 68],
     [102, 100, 98, 100]])
revenues = np.dot(M, R)
print(revenues)
column_sums = np.sum(revenues, axis=0)
print(column_sums)
largestIndex =0
max = 0
for i in range(len(column_sums)):
    if column_sums[i] > max:
        max = column_sums[i]
        largestIndex = i

print(f"It is concluded that maximum revenue is {max} and that is from {largestIndex+1} suggestion")

[[3170 3220 3210 3100]
 [1834 1812 1850 1836]
 [1954 1936 1924 1924]]
[6958 6968 6984 6860]
It is concluded that maximum revenue is 6984 and that is from 3 suggestion


### Marginal Cost (1 point)

The total cost $C(x)$ in Rupees, associated with the production of $x$ gallons of gasoline is given by

$$C(x) = 0.005 x^3 – 0.02 x^2 + 30x + 5000$$

Find the marginal cost when $22$ gallons are produced, where, marginal cost means the instantaneous rate of change of total cost at any level of output.

In [56]:
#TASK-13
# YOUR CODE HERE
import sympy as sp

# Define the symbol x
x = sp.symbols('x')
y = 0.005*(x**3) - .02*(x**2) + 30*x + 5000
# Compute the derivative dy/dx
dy_dx = sp.diff(y, x)
final_val = dy_dx.subs(x, 22)

# Print the result
print("The derivative of y with respect to x is:", dy_dx)
print("Final Value is :", final_val)

The derivative of y with respect to x is: 0.015*x**2 - 0.04*x + 30
Final Value is : 36.3800000000000


### Marginal Revenue (1 point)

The total revenue in Rupees received from the sale of $x$ gallons of a motor oil is given by $$R(x) = 3x^2 + 36x + 5.$$

Find the marginal revenue, when $x = 28$, where, marginal revenue means the rate of change of total revenue with respect to the number of items sold at an instant.

In [57]:
#TASK-14
# YOUR CODE HERE
import sympy as sp

# Define the symbol x
x = sp.symbols('x')
y = 3*(x**2) + 36*x + 5
# Compute the derivative dy/dx
dy_dx = sp.diff(y, x)
final_val = dy_dx.subs(x, 28)

# Print the result
print("The derivative of y with respect to x is:", dy_dx)
print("Final Value is :", final_val)

The derivative of y with respect to x is: 6*x + 36
Final Value is : 204


### Pouring crude oil in tank (1 point)

In a cylindrical tank of radius 10 meter, crude oil is being poured at the rate of 314 cubic meter per hour. Then find

* the rate at which the height of crude oil is increasing in the tank, and
* the height of crude oil in tank after 2 hours.

In [58]:
#TASK-15
# YOUR CODE HERE
#Formular for cylinder volume πr2h
import math
heightRate=round(314/(math.pi*10**2))
print(f"heightRate = {heightRate}")
print(f"After 2 hours = {heightRate*2}")

heightRate = 1
After 2 hours = 2
